
isbn_service1:
  restart: always
  build: src
  environment:
    VIRTUAL_HOST:  a.domain.com

web:
  restart: always
  build: web
  environment:
    VIRTUAL_HOST:  b.domain.com

nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  restart: always
  privileged: true