name: isbn_service_frontend
description: Port of ...
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  polymer: 1.0.0-rc.9
  reflectable: 0.4.0
  web_components: ^0.12.0

transformers:
- web_components:
    entry_points:
    - web/index.html
- reflectable:
    entry_points:
    - web/index.dart

